// packages/kliveide-emu/src/renderer/controls/Cz88Keyboard.svelte
<script>
  import { onMount } from "svelte";
  import Cz88Key from "./Cz88Key.svelte";
  import { defaultZ88KeyboardLayout } from "../machines/cz88/key-layout-default";
  import { esZ88KeyboardLayout } from "../machines/cz88/key-layout-es";
  import { frZ88KeyboardLayout } from "../machines/cz88/key-layout-fr";
  import { deZ88KeyboardLayout } from "../machines/cz88/key-layout-de";
  import { dkZ88KeyboardLayout } from "../machines/cz88/key-layout-dk";
  import { seZ88KeyboardLayout } from "../machines/cz88/key-layout-se";

  export let vmEngine;
  export let clientWidth;
  export let clientHeight;
  export let layout;

  let zoom = 1.0;
  const defaultWidth = 15 * 108 + 200 + 48;
  const defaultHeight = 5 * (100 + 8) + 48;

  // --- Special key codes
  const LEFT_SHIFT_KEY = 54;
  const SQUARE_KEY = 62;
  const DIAMOND_KEY = 52;

  let clo;

  onMount(async () => {
    calculateDimensions(clientWidth, clientHeight, defaultWidth, defaultHeight);
  });

  // --- Respond to panel size changes
  $: {
    calculateDimensions(clientWidth, clientHeight, defaultWidth, defaultHeight);
  }

  $: cz88 = vmEngine;

  $: {
    switch (layout) {
      case "es":
        clo = esZ88KeyboardLayout;
        break;
      case "fr":
        clo = frZ88KeyboardLayout;
        break;
      case "de":
        clo = deZ88KeyboardLayout;
        break;
      case "dk":
        clo = dkZ88KeyboardLayout;
        break;
      case "se":
        clo = seZ88KeyboardLayout;
        break;
      default:
        clo = defaultZ88KeyboardLayout;
        break;
    }
  }

  function calculateDimensions(clientWidth, clientHeight, width, height) {
    if (!clientWidth || !clientHeight) return;
    let widthRatio = (clientWidth - 24) / width;
    let heightRatio = (clientHeight - 32) / height;
    zoom = Math.min(widthRatio, heightRatio);
  }

  // --- Handles the mouse action
  function handleMouse(e) {
    // --- Set status of the primary key
    const ev = e.detail;
    cz88.setKeyStatus(ev.code, ev.isDown);

    // --- Set status of the secondary key
    switch (ev.iconCount) {
      case 1:
        if (!ev.isLeft) {
          cz88.setKeyStatus(LEFT_SHIFT_KEY, ev.isDown);
        }
        break;
      case 2:
        if (ev.target === "symbol") {
          cz88.setKeyStatus(ev.isLeft ? LEFT_SHIFT_KEY : SQUARE_KEY, ev.isDown);
        }
        break;
      case 3:
      if (ev.target === "key" && !ev.isLeft) {
          cz88.setKeyStatus(LEFT_SHIFT_KEY, ev.isDown);
        } else if (ev.target === "symbol") {
          if (ev.special === "dk") {
            cz88.setKeyStatus(SQUARE_KEY, ev.isDown);
          } else {
            cz88.setKeyStatus(ev.isLeft ? LEFT_SHIFT_KEY : SQUARE_KEY, ev.isDown);
          }
        } else if (ev.target === "secondSymbol" && ev.isLeft) {
          cz88.setKeyStatus(DIAMOND_KEY, ev.isDown);
        }
        break;
    }
  }
</script>

<div class="keyboard">
  <div class="key-row">
    <Cz88Key {zoom} code={61} layoutInfo={clo.Escape} on:do={handleMouse} />
    <Cz88Key {zoom} code={45} layoutInfo={clo.N1} on:do={handleMouse} />
    <Cz88Key {zoom} code={37} layoutInfo={clo.N2} on:do={handleMouse} />
    <Cz88Key {zoom} code={29} layoutInfo={clo.N3} on:do={handleMouse} />
    <Cz88Key {zoom} code={21} layoutInfo={clo.N4} on:do={handleMouse} />
    <Cz88Key {zoom} code={13} layoutInfo={clo.N5} on:do={handleMouse} />
    <Cz88Key {zoom} code={5} layoutInfo={clo.N6} on:do={handleMouse} />
    <Cz88Key {zoom} code={1} layoutInfo={clo.N7} on:do={handleMouse} />
    <Cz88Key {zoom} code={0} layoutInfo={clo.N8} on:do={handleMouse} />
    <Cz88Key {zoom} code={24} layoutInfo={clo.N9} on:do={handleMouse} />
    <Cz88Key {zoom} code={40} layoutInfo={clo.N0} on:do={handleMouse} />
    <Cz88Key {zoom} code={31} layoutInfo={clo.Minus} on:do={handleMouse} />
    <Cz88Key {zoom} code={23} layoutInfo={clo.Equal} on:do={handleMouse} />
    <Cz88Key {zoom} code={15} layoutInfo={clo.Backslash} on:do={handleMouse} />
    <Cz88Key {zoom} code={7} layoutInfo={clo.Delete} on:do={handleMouse} />
  </div>
  <div class="key-row-2-3">
    <div style="margin:0">
      <div class="key-row">
        <Cz88Key
          {zoom}
          code={53}
          layoutInfo={clo.Tab}
          on:do={handleMouse}
          xwidth="140"
        />
        <Cz88Key {zoom} code={44} layoutInfo={clo.Q} on:do={handleMouse} />
        <Cz88Key {zoom} code={36} layoutInfo={clo.W} on:do={handleMouse} />
        <Cz88Key {zoom} code={28} layoutInfo={clo.E} on:do={handleMouse} />
        <Cz88Key {zoom} code={20} layoutInfo={clo.R} on:do={handleMouse} />
        <Cz88Key {zoom} code={12} layoutInfo={clo.T} on:do={handleMouse} />
        <Cz88Key {zoom} code={4} layoutInfo={clo.Y} on:do={handleMouse} />
        <Cz88Key {zoom} code={9} layoutInfo={clo.U} on:do={handleMouse} />
        <Cz88Key {zoom} code={8} layoutInfo={clo.I} on:do={handleMouse} />
        <Cz88Key {zoom} code={16} layoutInfo={clo.O} on:do={handleMouse} />
        <Cz88Key {zoom} code={32} layoutInfo={clo.P} on:do={handleMouse} />
        <Cz88Key
          {zoom}
          code={47}
          layoutInfo={clo.SBracketL}
          on:do={handleMouse}
        />
        <Cz88Key
          {zoom}
          code={39}
          layoutInfo={clo.SBracketR}
          on:do={handleMouse}
        />
      </div>
      <div class="key-row">
        <Cz88Key
          {zoom}
          code={52}
          layoutInfo={clo.Diamond}
          on:do={handleMouse}
          vshift={8}
          fontSize={60}
          xwidth="180"
        />
        <Cz88Key {zoom} code={43} layoutInfo={clo.A} on:do={handleMouse} />
        <Cz88Key {zoom} code={35} layoutInfo={clo.S} on:do={handleMouse} />
        <Cz88Key {zoom} code={27} layoutInfo={clo.D} on:do={handleMouse} />
        <Cz88Key {zoom} code={19} layoutInfo={clo.F} on:do={handleMouse} />
        <Cz88Key {zoom} code={11} layoutInfo={clo.G} on:do={handleMouse} />
        <Cz88Key {zoom} code={3} layoutInfo={clo.H} on:do={handleMouse} />
        <Cz88Key {zoom} code={17} layoutInfo={clo.J} on:do={handleMouse} />
        <Cz88Key {zoom} code={25} layoutInfo={clo.K} on:do={handleMouse} />
        <Cz88Key {zoom} code={41} layoutInfo={clo.L} on:do={handleMouse} />
        <Cz88Key
          {zoom}
          code={49}
          layoutInfo={clo.Semicolon}
          on:do={handleMouse}
        />
        <Cz88Key {zoom} code={48} layoutInfo={clo.Quote} on:do={handleMouse} />
        <Cz88Key {zoom} code={56} layoutInfo={clo.Pound} on:do={handleMouse} />
      </div>
    </div>
    <div class="enter">
      <Cz88Key
        {zoom}
        code={6}
        on:do={handleMouse}
        isEnter={true}
        xwidth={122}
        xheight={200}
      />
    </div>
  </div>
  <div class="key-row">
    <Cz88Key
      {zoom}
      code={54}
      layoutInfo={clo.ShiftL}
      on:do={handleMouse}
      xwidth="240"
    />
    <Cz88Key {zoom} code={42} layoutInfo={clo.Z} on:do={handleMouse} />
    <Cz88Key {zoom} code={34} layoutInfo={clo.X} on:do={handleMouse} />
    <Cz88Key {zoom} code={26} layoutInfo={clo.C} on:do={handleMouse} />
    <Cz88Key {zoom} code={18} layoutInfo={clo.V} on:do={handleMouse} />
    <Cz88Key {zoom} code={10} layoutInfo={clo.B} on:do={handleMouse} />
    <Cz88Key {zoom} code={2} layoutInfo={clo.N} on:do={handleMouse} />
    <Cz88Key {zoom} code={33} layoutInfo={clo.M} on:do={handleMouse} />
    <Cz88Key {zoom} code={50} layoutInfo={clo.Comma} on:do={handleMouse} />
    <Cz88Key {zoom} code={58} layoutInfo={clo.Period} on:do={handleMouse} />
    <Cz88Key {zoom} code={57} layoutInfo={clo.Slash} on:do={handleMouse} />
    <Cz88Key
      {zoom}
      code={63}
      layoutInfo={clo.ShiftR}
      on:do={handleMouse}
      xwidth="160"
    />
    <Cz88Key
      {zoom}
      code={14}
      layoutInfo={clo.Up}
      on:do={handleMouse}
      vshift={8}
      fontSize={60}
    />
  </div>
  <div class="key-row">
    <Cz88Key {zoom} code={60} layoutInfo={clo.Index} on:do={handleMouse} />
    <Cz88Key {zoom} code={51} layoutInfo={clo.Menu} on:do={handleMouse} />
    <Cz88Key {zoom} code={55} layoutInfo={clo.Help} on:do={handleMouse} />
    <Cz88Key
      {zoom}
      code={62}
      layoutInfo={clo.Square}
      on:do={handleMouse}
      vshift={8}
      fontSize={60}
    />
    <Cz88Key
      {zoom}
      code={46}
      layoutInfo={clo.Space}
      on:do={handleMouse}
      xwidth="702"
    />
    <Cz88Key {zoom} code={59} on:do={handleMouse} top="CAPS" bottom="LOCK" />
    <Cz88Key
      {zoom}
      code={38}
      layoutInfo={clo.Left}
      on:do={handleMouse}
      fontSize={60}
      vshift={8}
    />
    <Cz88Key
      {zoom}
      code={30}
      layoutInfo={clo.Right}
      on:do={handleMouse}
      vshift={8}
      fontSize={60}
    />
    <Cz88Key
      {zoom}
      code={22}
      layoutInfo={clo.Down}
      on:do={handleMouse}
      vshift={8}
      fontSize={60}
    />
  </div>
</div>

<style>
  .keyboard {
    display: flex;
    flex-direction: column;
    flex-shrink: 0;
    flex-grow: 0;
    height: 100%;
    background-color: transparent;
    box-sizing: border-box;
    align-content: start;
    justify-items: start;
    justify-content: center;
    overflow: hidden;
  }

  .key-row {
    padding: 0px 0px;
    margin: 0;
    display: flex;
    flex-grow: 0;
    flex-shrink: 0;
    font-weight: bold;
  }

  .key-row-2-3 {
    display: flex;
    flex-direction: row;
    flex-grow: 0;
    flex-shrink: 0;
    margin: 0;
  }

  .enter {
    display: flex;
    flex-grow: 0;
    flex-shrink: 0;
    font-weight: bold;
    margin: 0;
  }
</style>

// src/renderer/emulator/Cz88Keyboard.tsx
import * as React from "react";

import { Z88ButtonClickArgs } from "./ui-core-types";
import Key from "./Cz88Key";
import styles from "styled-components";
import { Cz88KeyboardLayout } from "@ext/vm-z88/cz88-keys";
import { esZ88KeyboardLayout } from "@ext/vm-z88/key-layout-es";
import { frZ88KeyboardLayout } from "@ext/vm-z88/key-layout-fr";
import { deZ88KeyboardLayout } from "@ext/vm-z88/key-layout-de";
import { dkZ88KeyboardLayout } from "@ext/vm-z88/key-layout-dk";
import { seZ88KeyboardLayout } from "@ext/vm-z88/key-layout-se";
import { defaultZ88KeyboardLayout } from "@ext/vm-z88/key-layout-default";
import { getVmEngineService } from "@ext-core/vm-engine-service";
import { CambridgeZ88Core } from "@ext/vm-z88/CambridgeZ88Core";

const DEFAULT_WIDTH = 15 * 108 + 200 + 48;
const DEFAULT_HEIGHT = 5 * (100 + 8) + 48;

// --- Special key codes
const LEFT_SHIFT_KEY = 54;
const SQUARE_KEY = 62;
const DIAMOND_KEY = 52;

/**
 * Component properties
 */
interface Props {
  width: number;
  height: number;
  layout?: string;
}

/**
 * Represents the keyboard of Czmbridge Z88
 */
export default function Cz88Keyboard(props: Props) {
  // --- Prepare keyboard layout information
  let l: Cz88KeyboardLayout;
  switch (props.layout) {
    case "es":
      l = esZ88KeyboardLayout;
      break;
    case "fr":
      l = frZ88KeyboardLayout;
      break;
    case "de":
      l = deZ88KeyboardLayout;
      break;
    case "dk":
      l = dkZ88KeyboardLayout;
      break;
    case "se":
      l = seZ88KeyboardLayout;
      break;
    default:
      l = defaultZ88KeyboardLayout;
      break;
  }
  const zoom = calculateZoom(props.width, props.height);

  return (
    <Root>
      <KeyRow>
        <Key zoom={zoom} code={61} layoutInfo={l.Escape} keyAction={click} />
        <Key zoom={zoom} code={45} layoutInfo={l.N1} keyAction={click} />
        <Key zoom={zoom} code={37} layoutInfo={l.N2} keyAction={click} />
        <Key zoom={zoom} code={29} layoutInfo={l.N3} keyAction={click} />
        <Key zoom={zoom} code={21} layoutInfo={l.N4} keyAction={click} />
        <Key zoom={zoom} code={13} layoutInfo={l.N5} keyAction={click} />
        <Key zoom={zoom} code={5} layoutInfo={l.N6} keyAction={click} />
        <Key zoom={zoom} code={1} layoutInfo={l.N7} keyAction={click} />
        <Key zoom={zoom} code={0} layoutInfo={l.N8} keyAction={click} />
        <Key zoom={zoom} code={24} layoutInfo={l.N9} keyAction={click} />
        <Key zoom={zoom} code={40} layoutInfo={l.N0} keyAction={click} />
        <Key zoom={zoom} code={31} layoutInfo={l.Minus} keyAction={click} />
        <Key zoom={zoom} code={23} layoutInfo={l.Equal} keyAction={click} />
        <Key zoom={zoom} code={15} layoutInfo={l.Backslash} keyAction={click} />
        <Key zoom={zoom} code={7} layoutInfo={l.Delete} keyAction={click} />
      </KeyRow>
      <KeyRow2To3>
        <div style={{ margin: 0 }}>
          <KeyRow>
            <Key
              zoom={zoom}
              code={53}
              layoutInfo={l.Tab}
              keyAction={click}
              xwidth={140}
            />
            <Key zoom={zoom} code={44} layoutInfo={l.Q} keyAction={click} />
            <Key zoom={zoom} code={36} layoutInfo={l.W} keyAction={click} />
            <Key zoom={zoom} code={28} layoutInfo={l.E} keyAction={click} />
            <Key zoom={zoom} code={20} layoutInfo={l.R} keyAction={click} />
            <Key zoom={zoom} code={12} layoutInfo={l.T} keyAction={click} />
            <Key zoom={zoom} code={4} layoutInfo={l.Y} keyAction={click} />
            <Key zoom={zoom} code={9} layoutInfo={l.U} keyAction={click} />
            <Key zoom={zoom} code={8} layoutInfo={l.I} keyAction={click} />
            <Key zoom={zoom} code={16} layoutInfo={l.O} keyAction={click} />
            <Key zoom={zoom} code={32} layoutInfo={l.P} keyAction={click} />
            <Key
              zoom={zoom}
              code={47}
              layoutInfo={l.SBracketL}
              keyAction={click}
            />
            <Key
              zoom={zoom}
              code={39}
              layoutInfo={l.SBracketR}
              keyAction={click}
            />
          </KeyRow>
          <KeyRow>
            <Key
              zoom={zoom}
              code={52}
              layoutInfo={l.Diamond}
              keyAction={click}
              vshift={8}
              fontSize={60}
              xwidth={180}
            />
            <Key zoom={zoom} code={43} layoutInfo={l.A} keyAction={click} />
            <Key zoom={zoom} code={35} layoutInfo={l.S} keyAction={click} />
            <Key zoom={zoom} code={27} layoutInfo={l.D} keyAction={click} />
            <Key zoom={zoom} code={19} layoutInfo={l.F} keyAction={click} />
            <Key zoom={zoom} code={11} layoutInfo={l.G} keyAction={click} />
            <Key zoom={zoom} code={3} layoutInfo={l.H} keyAction={click} />
            <Key zoom={zoom} code={17} layoutInfo={l.J} keyAction={click} />
            <Key zoom={zoom} code={25} layoutInfo={l.K} keyAction={click} />
            <Key zoom={zoom} code={41} layoutInfo={l.L} keyAction={click} />
            <Key
              zoom={zoom}
              code={49}
              layoutInfo={l.Semicolon}
              keyAction={click}
            />
            <Key zoom={zoom} code={48} layoutInfo={l.Quote} keyAction={click} />
            <Key zoom={zoom} code={56} layoutInfo={l.Pound} keyAction={click} />
          </KeyRow>
        </div>
        <EnterContainer>
          <Key
            zoom={zoom}
            code={6}
            keyAction={click}
            isEnter={true}
            xwidth={122}
            xheight={200}
          />
        </EnterContainer>
      </KeyRow2To3>
      <KeyRow>
        <Key
          zoom={zoom}
          code={54}
          layoutInfo={l.ShiftL}
          keyAction={click}
          xwidth={240}
        />
        <Key zoom={zoom} code={42} layoutInfo={l.Z} keyAction={click} />
        <Key zoom={zoom} code={34} layoutInfo={l.X} keyAction={click} />
        <Key zoom={zoom} code={26} layoutInfo={l.C} keyAction={click} />
        <Key zoom={zoom} code={18} layoutInfo={l.V} keyAction={click} />
        <Key zoom={zoom} code={10} layoutInfo={l.B} keyAction={click} />
        <Key zoom={zoom} code={2} layoutInfo={l.N} keyAction={click} />
        <Key zoom={zoom} code={33} layoutInfo={l.M} keyAction={click} />
        <Key zoom={zoom} code={50} layoutInfo={l.Comma} keyAction={click} />
        <Key zoom={zoom} code={58} layoutInfo={l.Period} keyAction={click} />
        <Key zoom={zoom} code={57} layoutInfo={l.Slash} keyAction={click} />
        <Key
          zoom={zoom}
          code={63}
          layoutInfo={l.ShiftR}
          keyAction={click}
          xwidth={160}
        />
        <Key
          zoom={zoom}
          code={14}
          layoutInfo={l.Up}
          keyAction={click}
          vshift={8}
          fontSize={60}
        />
      </KeyRow>
      <KeyRow>
        <Key zoom={zoom} code={60} layoutInfo={l.Index} keyAction={click} />
        <Key zoom={zoom} code={51} layoutInfo={l.Menu} keyAction={click} />
        <Key zoom={zoom} code={55} layoutInfo={l.Help} keyAction={click} />
        <Key
          zoom={zoom}
          code={62}
          layoutInfo={l.Square}
          keyAction={click}
          vshift={8}
          fontSize={60}
        />
        <Key
          zoom={zoom}
          code={46}
          layoutInfo={l.Space}
          keyAction={click}
          xwidth={702}
        />
        <Key zoom={zoom} code={59} keyAction={click} top="CAPS" bottom="LOCK" />
        <Key
          zoom={zoom}
          code={38}
          layoutInfo={l.Left}
          keyAction={click}
          fontSize={60}
          vshift={8}
        />
        <Key
          zoom={zoom}
          code={30}
          layoutInfo={l.Right}
          keyAction={click}
          vshift={8}
          fontSize={60}
        />
        <Key
          zoom={zoom}
          code={22}
          layoutInfo={l.Down}
          keyAction={click}
          vshift={8}
          fontSize={60}
        />
      </KeyRow>
    </Root>
  );

  function click(e: Z88ButtonClickArgs): void {
    const vmEngineService = getVmEngineService();
    if (!vmEngineService.hasEngine) {
      // --- No engine
      return;
    }
    const engine = vmEngineService.getEngine() as CambridgeZ88Core

    // --- Set status of the primary key
    engine.setKeyStatus(e.code, e.down);

    // --- Set status of the secondary key
    switch (e.iconCount) {
      case 0:
      case 1:
        if (!e.isLeft) {
          engine.setKeyStatus(LEFT_SHIFT_KEY, e.down);
        }
        break;
      case 2:
        if (e.keyCategory === "symbol") {
          engine.setKeyStatus(e.isLeft ? LEFT_SHIFT_KEY : SQUARE_KEY, e.down);
        }
        break;
      case 3:
        if (e.keyCategory === "key" && !e.isLeft) {
          engine.setKeyStatus(LEFT_SHIFT_KEY, e.down);
        } else if (e.keyCategory === "symbol") {
          if (e.special === "dk") {
            engine.setKeyStatus(SQUARE_KEY, e.down);
          } else {
            engine.setKeyStatus(e.isLeft ? LEFT_SHIFT_KEY : SQUARE_KEY, e.down);
          }
        } else if (e.keyCategory === "secondSymbol" && e.isLeft) {
          engine.setKeyStatus(DIAMOND_KEY, e.down);
        }
        break;
    }
  }

  function calculateZoom(width: number, height: number): number {
    if (!width || !height) return 0.05;
    let widthRatio = (width - 24) / DEFAULT_WIDTH;
    let heightRatio = (height - 32) / DEFAULT_HEIGHT;
    return Math.min(widthRatio, heightRatio);
  }
}

// --- Helper component tags
const Root = styles.div`
  display: flex;
  flex-direction: column;
  flex-shrink: 0;
  flex-grow: 0;
  height: 100%;
  background-color: transparent;
  box-sizing: border-box;
  align-content: start;
  justify-items: start;
  justify-content: center;
  overflow: hidden;
`;

const KeyRow = styles.div`
  padding: 0px 0px;
  margin: 0;
  display: flex;
  flex-grow: 0;
  flex-shrink: 0;
  font-weight: bold;
`;

const KeyRow2To3 = styles.div`
  display: flex;
  flex-direction: row;
  flex-grow: 0;
  flex-shrink: 0;
  margin: 0;
`;

const EnterContainer = styles.div`
  display: flex;
  flex-grow: 0;
  flex-shrink: 0;
  font-weight: bold;
  margin: 0;
`;
