// packages/kliveide-emu/src/renderer/controls/Cz88Key.svelte
<script>
  // ==========================================================================
  // Represents a key in the ZX Spectrum 48 keyboard

  import { createEventDispatcher } from "svelte";
  import { themeStore } from "../stores/theme-store";

  // --- Current zoom factor
  export let zoom = 1.0;

  // --- Layout information
  export let layoutInfo;

  // --- Number of clickable icons
  export let iconCount;

  // --- Z88 key code
  export let code;

  // --- Main text to be put to the top of the key
  export let top;

  // --- Main text to be put to the bottom of the key
  export let bottom;

  // --- Extra width to use instead of the default
  export let xwidth;

  // --- Extra height to use instead of the default
  export let xheight;

  // --- Extra verical shift;
  export let vshift;

  // --- Extra font size for keywords
  export let fontSize;

  export let isEnter = false;

  // --- Dimensions
  const normalWidth = 100;
  let mouseOverKey = false;
  let mouseOverSymbol = false;
  let mouseOverSecondSymbol = false;

  // --- Key icons to display
  let key;
  let keyword;
  let symbol;
  let secondSymbol;

  // --- Colors
  const keyBackground = themeStore.getProperty("--key-cz88-background-color");
  const mainKeyColor = themeStore.getProperty("--key-cz88-main-color");
  const keyStrokeColor = themeStore.getProperty("--key-cz88-stroke-color");
  const symbolKeyColor = themeStore.getProperty("--key-cz88-main-color");
  const highlightKeyColor = themeStore.getProperty(
    "--key-cz88-highlight-color"
  );

  // --- Reactive expressions for layout
  $: {
    if (layoutInfo) {
      keyword = layoutInfo.keyword;
      key = layoutInfo.key;
      symbol = layoutInfo.symbol;
      secondSymbol = layoutInfo.secondSymbol;
    }
    iconCount = 0;
    if (key) iconCount++;
    if (symbol) iconCount++;
    if (secondSymbol) iconCount++;
  }

  // --- Reactive expressions for button dimensions
  $: normalHeight = 100;
  $: currentWidth = zoom * (xwidth || normalWidth);
  $: currentHeight = zoom * (xheight || normalHeight);
  $: mainFillColor = mouseOverKey ? highlightKeyColor : mainKeyColor;
  $: mainStrokeColor = mouseOverKey ? highlightKeyColor : "transparent";
  $: symbolFillColor = mouseOverSymbol ? highlightKeyColor : symbolKeyColor;
  $: symbolStrokeColor = mouseOverSymbol ? highlightKeyColor : "transparent";
  $: secondSymbolFillColor = mouseOverSecondSymbol
    ? highlightKeyColor
    : symbolKeyColor;
  $: secondSymbolStrokeColor = mouseOverSecondSymbol
    ? highlightKeyColor
    : "transparent";
  $: cursor = mouseOverKey | mouseOverSymbol ? "pointer" : "default";

  // --- This component raises a "clicked" event
  const dispatch = createEventDispatcher();

  // --- Notify parent about the key action
  function keyAction(e, target, isDown) {
    dispatch("do", {
      code,
      target,
      isDown,
      isLeft: e.button === 0,
      iconCount,
      special: layoutInfo ? layoutInfo.special : undefined
    });
  }
</script>

<svg
  width={currentWidth}
  height={currentHeight}
  viewBox="0 0 {parseInt(xwidth || normalWidth) + 20} {parseInt(
    xheight || normalHeight
  ) + 20}"
  style="margin:0"
  preserveAspectRatio="none"
  xmlns="http://www.w3.org/2000/svg">
  <rect
    x="2"
    y="2"
    rx="12"
    ry="12"
    width={xwidth || normalWidth}
    height={xheight || normalHeight}
    fill={keyBackground}
    stroke={keyStrokeColor}
    stroke-width="4"
    {cursor}
    on:mouseenter={() => (mouseOverKey = true)}
    on:mouseleave={() => (mouseOverKey = false)}
    on:mousedown={(e) => keyAction(e, "key", true)}
    on:mouseup={(e) => keyAction(e, "key", false)}
  />
  {#if key}
    <text
      x="14"
      y="88"
      font-size="36"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}>
      {key}
    </text>
  {/if}
  {#if symbol}
    <rect
      x="48"
      y="16"
      width={54}
      height={40}
      fill="transparent"
      {cursor}
      on:mouseenter={() => (mouseOverSymbol = true)}
      on:mouseleave={() => (mouseOverSymbol = false)}
      on:mousedown={(e) => keyAction(e, "symbol", true)}
      on:mouseup={(e) => keyAction(e, "symbol", false)}>
      {symbol}
    </rect>
    <text
      x="68"
      y="36"
      font-size={32}
      text-anchor="middle"
      fill={symbolFillColor}
      stroke={symbolStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverSymbol = true)}
      on:mouseleave={() => (mouseOverSymbol = false)}
      on:mousedown={(e) => keyAction(e, "symbol", true)}
      on:mouseup={(e) => keyAction(e, "symbol", false)}>
      {symbol}
    </text>
  {/if}
  {#if secondSymbol}
    <rect
      x="48"
      y="68"
      width={54}
      height={40}
      fill="transparent"
      {cursor}
      on:mouseenter={() => (mouseOverSecondSymbol = true)}
      on:mouseleave={() => (mouseOverSecondSymbol = false)}
      on:mousedown={(e) => keyAction(e, "secondSymbol", true)}
      on:mouseup={(e) => keyAction(e, "secondSymbol", false)}>
      {symbol}
    </rect>
    <text
      x="68"
      y="88"
      font-size={32}
      text-anchor="middle"
      fill={secondSymbolFillColor}
      stroke={secondSymbolStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverSecondSymbol = true)}
      on:mouseleave={() => (mouseOverSecondSymbol = false)}
      on:mousedown={(e) => keyAction(e, "secondSymbol", true)}
      on:mouseup={(e) => keyAction(e, "secondSymbol", false)}>
      {secondSymbol}
    </text>
  {/if}
  {#if keyword}
    <text
      x={(xwidth || 100) / 2}
      y={62 + (vshift || 0)}
      font-size={fontSize ? fontSize : 28}
      text-anchor="middle"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}>
      {keyword}
    </text>
  {/if}
  {#if top}
    <text
      x={(xwidth || 100) / 2}
      y={48}
      font-size="28"
      text-anchor="middle"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}>
      {top}
    </text>
  {/if}
  {#if bottom}
    <text
      x={(xwidth || 100) / 2}
      y={76}
      font-size="28"
      text-anchor="middle"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}>
      {bottom}
    </text>
  {/if}
  {#if isEnter}
    <text
      x={(xwidth || 100) / 2 - 6}
      y={54}
      font-size="28"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}> E </text>
    <text
      x={(xwidth || 100) / 2 - 6}
      y={84}
      font-size="28"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}> N </text>
    <text
      x={(xwidth || 100) / 2 - 6}
      y={114}
      font-size="28"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}> T </text>
    <text
      x={(xwidth || 100) / 2 - 6}
      y={144}
      font-size="28"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}> E </text>
    <text
      x={(xwidth || 100) / 2 - 6}
      y={174}
      font-size="28"
      text-anchor="left"
      fill={mainFillColor}
      stroke={mainStrokeColor}
      {cursor}
      on:mouseenter={() => (mouseOverKey = true)}
      on:mouseleave={() => (mouseOverKey = false)}
      on:mousedown={(e) => keyAction(e, "key", true)}
      on:mouseup={(e) => keyAction(e, "key", false)}> R </text>
  {/if}
</svg>

// src/emu/Cz88Key.tsx
import * as React from "react";
import { useState } from "react";

import { getThemeService } from "@core/service-registry";
import { Cz88KeyView } from "@ext/vm-z88/cz88-keys";
import { Z88ButtonClickArgs } from "./ui-core-types";

const NORMAL_WIDTH = 100;
const NORMAL_HEIGHT = 100;

/**
 * Component properties
 */
interface Props {
  zoom: number;
  code: number;
  layoutInfo?: Cz88KeyView;
  iconCount?: number;
  top?: string;
  bottom?: string;
  xwidth?: number;
  xheight?: number;
  vshift?: number;
  fontSize?: number;
  isEnter?: boolean;
  keyAction?: (e: Z88ButtonClickArgs, down: boolean) => void;
}

/**
 * Represents a key of the Cambridge Z88 keyboard
 */
export default function Cz88Key(props: Props) {
  // --- Component states
  const [mouseOverKey, setMouseOverKey] = useState(false);
  const [mouseOverSymbol, setMouseOverSymbol] = useState(false);
  const [mouseOverSecondSymbol, setMouseOverSecondSymbol] = useState(false);

  // --- Number of icons on the key
  let iconCount = 0;

  // --- Invariant display properties
  const themeService = getThemeService();
  const keyBackground = themeService.getProperty("--key-cz88-background-color");
  const mainKeyColor = themeService.getProperty("--key-cz88-main-color");
  const keyStrokeColor = themeService.getProperty("--key-cz88-stroke-color");
  const symbolKeyColor = themeService.getProperty("--key-cz88-main-color");
  const highlightKeyColor = themeService.getProperty(
    "--key-cz88-highlight-color"
  );

  // --- Prepare rendering
  let main = "";
  let keyword = "";
  let symbol = "";
  let secondSymbol;
  if (props.layoutInfo) {
    keyword = props.layoutInfo.keyword;
    main = props.layoutInfo.key;
    symbol = props.layoutInfo.symbol;
    secondSymbol = props.layoutInfo.secondSymbol;
  }
  iconCount = 0;
  if (main) iconCount++;
  if (symbol) iconCount++;
  if (secondSymbol) iconCount++;

  const currentWidth = props.zoom * (props.xwidth || NORMAL_WIDTH);
  const currentHeight = props.zoom * (props.xheight || NORMAL_HEIGHT);
  const mainFillColor = mouseOverKey ? highlightKeyColor : mainKeyColor;
  const mainStrokeColor = mouseOverKey ? highlightKeyColor : "transparent";
  const symbolFillColor = mouseOverSymbol ? highlightKeyColor : symbolKeyColor;
  const symbolStrokeColor = mouseOverSymbol ? highlightKeyColor : "transparent";
  const secondSymbolFillColor = mouseOverSecondSymbol
    ? highlightKeyColor
    : symbolKeyColor;
  const secondSymbolStrokeColor = mouseOverSecondSymbol
    ? highlightKeyColor
    : "transparent";
  const cursor = mouseOverKey || mouseOverSymbol ? "pointer" : "default";

  // --- Render
  return (
    <svg
      width={currentWidth}
      height={currentHeight}
      viewBox={`0 0 ${(props.xwidth || NORMAL_WIDTH) + 20} ${
        (props.xheight || NORMAL_HEIGHT) + 20
      }`}
      style={{ margin: 0 }}
      preserveAspectRatio="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect
        x="2"
        y="2"
        rx="12"
        ry="12"
        width={props.xwidth || NORMAL_WIDTH}
        height={props.xheight || NORMAL_HEIGHT}
        fill={keyBackground}
        stroke={keyStrokeColor}
        strokeWidth="4"
        cursor={cursor}
        onMouseEnter={() => setMouseOverKey(true)}
        onMouseLeave={() => setMouseOverKey(false)}
        onMouseDown={(e) => raiseKeyAction(e, "main", true)}
        onMouseUp={(e) => raiseKeyAction(e, "main", false)}
      />
      {main && (
        <text
          x="14"
          y="88"
          fontSize="36"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          {main}
        </text>
      )}
      {symbol && (
        <rect
          x="48"
          y="16"
          width={54}
          height={40}
          fill="transparent"
          cursor={cursor}
          onMouseEnter={() => setMouseOverSymbol(true)}
          onMouseLeave={() => setMouseOverSymbol(false)}
          onMouseDown={(e) => raiseKeyAction(e, "symbol", true)}
          onMouseUp={(e) => raiseKeyAction(e, "symbol", false)}
        >
          {symbol}
        </rect>
      )}
      {symbol && (
        <text
          x="68"
          y="36"
          fontSize={32}
          textAnchor="middle"
          fill={symbolFillColor}
          stroke={symbolStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverSymbol(true)}
          onMouseLeave={() => setMouseOverSymbol(false)}
          onMouseDown={(e) => raiseKeyAction(e, "symbol", true)}
          onMouseUp={(e) => raiseKeyAction(e, "symbol", false)}
        >
          {symbol}
        </text>
      )}
      {secondSymbol && (
        <rect
          x="48"
          y="68"
          width={54}
          height={40}
          fill="transparent"
          cursor={cursor}
          onMouseEnter={() => setMouseOverSecondSymbol(true)}
          onMouseLeave={() => setMouseOverSecondSymbol(true)}
          onMouseDown={(e) => raiseKeyAction(e, "secondsymbol", true)}
          onMouseUp={(e) => raiseKeyAction(e, "secondsymbol", false)}
        ></rect>
      )}
      {secondSymbol && (
        <text
          x="68"
          y="88"
          fontSize={32}
          textAnchor="middle"
          fill={secondSymbolFillColor}
          stroke={secondSymbolStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverSecondSymbol(true)}
          onMouseLeave={() => setMouseOverSecondSymbol(true)}
          onMouseDown={(e) => raiseKeyAction(e, "secondsymbol", true)}
          onMouseUp={(e) => raiseKeyAction(e, "secondsymbol", false)}
        >
          {secondSymbol}
        </text>
      )}
      {keyword && (
        <text
          x={(props.xwidth || 100) / 2}
          y={62 + (props.vshift || 0)}
          fontSize={props.fontSize ?? 28}
          textAnchor="middle"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          {keyword}
        </text>
      )}
      {props.top && (
        <text
          x={(props.xwidth || 100) / 2}
          y={48}
          fontSize="28"
          textAnchor="middle"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          {props.top}
        </text>
      )}
      {props.bottom && (
        <text
          x={(props.xwidth || 100) / 2}
          y={76}
          fontSize="28"
          textAnchor="middle"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          {props.bottom}
        </text>
      )}
      {props.isEnter && (
        <text
          x={(props.xwidth || 100) / 2 - 6}
          y={54}
          fontSize="28"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          E
        </text>
      )}
      {props.isEnter && (
        <text
          x={(props.xwidth || 100) / 2 - 6}
          y={84}
          fontSize="28"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          N
        </text>
      )}
      {props.isEnter && (
        <text
          x={(props.xwidth || 100) / 2 - 6}
          y={114}
          fontSize="28"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          T
        </text>
      )}
      {props.isEnter && (
        <text
          x={(props.xwidth || 100) / 2 - 6}
          y={144}
          fontSize="28"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          E
        </text>
      )}
      {props.isEnter && (
        <text
          x={(props.xwidth || 100) / 2 - 6}
          y={174}
          fontSize="28"
          textAnchor="left"
          fill={mainFillColor}
          stroke={mainStrokeColor}
          cursor={cursor}
          onMouseEnter={() => setMouseOverKey(true)}
          onMouseLeave={() => setMouseOverKey(false)}
          onMouseDown={(e) => raiseKeyAction(e, "main", true)}
          onMouseUp={(e) => raiseKeyAction(e, "main", false)}
        >
          R
        </text>
      )}
    </svg>
  );

  function raiseKeyAction(
    e: React.MouseEvent,
    keyCategory: string,
    down: boolean
  ) {
    props.keyAction?.(
      {
        code: props.code,
        keyCategory,
        down,
        isLeft: e.button === 0,
        iconCount: iconCount,
        special: props.layoutInfo ? props.layoutInfo.special : undefined,
      },
      down
    );
  }
}
