// packages/kliveide-emu/src/renderer/controls/ExecutionStateOverlay.svelte
<script>
  // ==========================================================================
  // Displays the overlay with the current Execution state
  import { createEventDispatcher } from "svelte";

  // --- Display this text, provided it's not empty
  export let text = "Overlay";

  // --- This control will dispatch a "hide" event on click
  const dispatch = createEventDispatcher();
</script>

<style>
  .play-overlay {
    position: relative;
    flex-shrink: 0;
    flex-grow: 0;
    height: 0;
    left: 8px;
    top: 8px;
  }

  .overlay-text {
    display: inline-block;
    background-color: #404040;
    color: lightgreen;
    opacity: 0.9;
    padding: 2px 10px 4px 10px;
    border-radius: 4px;
    cursor: pointer;
  }
</style>

{#if text}
<div class="play-overlay">
  <span class="overlay-text" title="Hide overlay (click to show again)"
  on:click|stopPropagation={() => dispatch("hide")}>{text}</span>
</div>
{/if}

// src/emu/ExecutionStateOverlay.tsx
import * as React from "react";
import { CSSProperties } from "react";

interface Props {
  text: string;
  clicked?: () => void;
}

/**
 * Represents the overlay of the emulator's panel
 */
export default function ExecutionStateOverlay(props: Props) {
  if (props.text) {
    return (
      <div style={rootStyle} onClick={handleClick}>
        <div style={overlayStyle} title="Hide overlay (click to show again)">
          {props.text}
        </div>
      </div>
    );
  } else {
    return null;
  }

  function handleClick(e: React.MouseEvent): void {
    e.stopPropagation();
    props.clicked?.();
  }
}

const rootStyle: CSSProperties = {
  position: "relative",
  flexShrink: 0,
  flexGrow: 0,
  height: 0,
  left: 8,
  top: 8,
  marginRight: 16,
};

const overlayStyle: CSSProperties = {
  display: "inline-block",
  backgroundColor: "#404040",
  color: "lightgreen",
  opacity: 0.9,
  padding: "2px 10px 4px 10px",
  borderRadius: 4,
  cursor: "pointer"
}
