// packages/kliveide-emu/src/renderer/controls/Toolbar.svelte
<script>
  // ==========================================================================
  // The singleton toolbar of the application

  import ToolbarIconButton from "./ToolbarIconButton.svelte";
  import ToolbarSeparator from "./ToolbarSeparator.svelte";

  import { themeStore } from "../stores/theme-store";
  import { createRendererProcessStateAware } from "../rendererProcessStore";
  import {
    emulatorToggleKeyboardAction,
    emulatorToggleShadowScreenAction,
    emulatorToggleBeamPositionAction,
    emulatorToggleFastLoadAction,
    emulatorMuteAction,
    emulatorUnmuteAction,
  } from "../../shared/state/redux-emulator-state";

  // --- The virtual machine instance
  export let vmEngine;

  // --- We change Titlebar colors as the app focus changes
  let backgroundColor;
  let keyboardDisplayed;
  let shadowScreenEnabled;
  let beamPositionEnabled;
  let fastLoadEnabled;
  let isLoading;
  let muted;
  let extraFeatures = [];

  calculateColors(true); // --- Default: the app has the focus

  let executionState = 0;

  // --- Respond to the event when app focus changes
  const stateAware = createRendererProcessStateAware();
  stateAware.stateChanged.on(async (state) => {
    // --- Change the UI according to state change
    const emuUi = state.emulatorPanelState;
    if (emuUi) {
      keyboardDisplayed = emuUi.keyboardPanel;
      shadowScreenEnabled = emuUi.shadowScreen;
      beamPositionEnabled = emuUi.beamPosition;
      fastLoadEnabled = emuUi.fastLoad;
      isLoading = emuUi.isLoading;
      muted = emuUi.muted;
    }
    calculateColors(state.appHasFocus);
  });

  // --- Watch the execution state change of the virtual machine
  $: {
    if (vmEngine) {
      extraFeatures = vmEngine.z80Machine.getExtraMachineFeatures();
      vmEngine.executionStateChanged.on(({ newState }) => {
        executionState = newState;
      });
    }
  }

  // --- Calculate colors according to focus state
  function calculateColors(focused) {
    let propName = focused
      ? "--toolbar-active-background-color"
      : "--toolbar-inactive-background-color";
    backgroundColor = themeStore.getProperty(propName);
  }
</script>

<style>
  .toolbar {
    display: flex;
    flex-shrink: 0;
    flex-grow: 0;
    height: 40px;
    width: 100%;
    padding: 0px 4px;
    background-color: var(--toolbar-background-color);
    box-sizing: border-box;
    align-items: center;
    justify-content: start;
    font-size: 0.9em;
  }
</style>

{#if vmEngine}
  <div class="toolbar" style="background-color:{backgroundColor}">
    <ToolbarIconButton
      iconName="play"
      fill="lightgreen"
      title="Start"
      enable={executionState === 0 || executionState === 3 || executionState === 5}
      on:clicked={async () => await vmEngine.start()} />
    <ToolbarIconButton
      iconName="pause"
      fill="lightblue"
      title="Stop"
      enable={executionState === 1}
      on:clicked={async () => await vmEngine.pause()} />
    <ToolbarIconButton
      iconName="stop"
      fill="orangered"
      title="Pause"
      enable={executionState === 1 || executionState === 3}
      on:clicked={async () => await vmEngine.stop()} />
    <ToolbarIconButton
      iconName="restart"
      fill="lightgreen"
      title="Reset"
      size="22"
      highlightSize="26"
      enable={executionState === 1 || executionState === 3}
      on:clicked={async () => await vmEngine.restart()} />
    <ToolbarSeparator />
    <ToolbarIconButton
      iconName="debug"
      fill="lightgreen"
      title="Debug"
      size="20"
      highlightSize="24"
      enable={executionState === 0 || executionState === 3 || executionState === 5}
      on:clicked={async () => await vmEngine.startDebug()} />
    <ToolbarIconButton
      iconName="step-into"
      fill="lightblue"
      title="Step into"
      enable={executionState === 3}
      on:clicked={async () => await vmEngine.stepInto()} />
    <ToolbarIconButton
      iconName="step-over"
      fill="lightblue"
      title="Step over"
      enable={executionState === 3}
      on:clicked={async () => await vmEngine.stepOver()} />
    <ToolbarIconButton
      iconName="step-out"
      fill="lightblue"
      title="Step out"
      enable={executionState === 3}
      on:clicked={async () => await vmEngine.stepOut()} />
    <ToolbarSeparator />
    <ToolbarIconButton
      iconName="keyboard"
      title="Toggle keyboard"
      highlightSize="32"
      selected={keyboardDisplayed}
      on:clicked={() => {
        stateAware.dispatch(emulatorToggleKeyboardAction());
      }} />
    <ToolbarSeparator />
    {#if extraFeatures.includes('UlaDebug')}
    <ToolbarIconButton
      iconName="beam-position"
      fill="#ff80ff"
      title="Show ULA position"
      selected={beamPositionEnabled}
      on:clicked={() => {
        stateAware.dispatch(emulatorToggleBeamPositionAction());
      }} />
    <ToolbarSeparator />
    {/if}
    {#if extraFeatures.includes('Sound')}
      {#if muted}
        <ToolbarIconButton
          iconName="unmute"
          title="Unmute sound"
          on:clicked={() => {
            stateAware.dispatch(emulatorUnmuteAction());
          }} />
      {:else}
        <ToolbarIconButton
          iconName="mute"
          title="Mute sound"
          on:clicked={() => {
            stateAware.dispatch(emulatorMuteAction());
          }} />
      {/if}
      <ToolbarSeparator />
      {/if}
    {#if extraFeatures.includes('Tape')}
      <ToolbarIconButton
      iconName="rocket"
      title="Fast LOAD mode"
      selected={fastLoadEnabled}
      on:clicked={() => {
        stateAware.dispatch(emulatorToggleFastLoadAction());
      }} />
    <ToolbarIconButton
      iconName="reverse-tape"
      title="Rewind the tape"
      enable={!isLoading}
      on:clicked={() => vmEngine.initTapeContents('Tape rewound')} />
      <ToolbarSeparator />
    {/if}
  </div>
{/if}

// src/emu/Toolbar.tsx
import * as React from "react";
import { connect } from "react-redux";
import styles from "styled-components";

import { dispatch } from "@core/service-registry";
import { AppState } from "@state/AppState";
import { ToolbarIconButton } from "@components/ToolbarIconButton";
import { ToolbarSeparator } from "@components/ToolbarSeparator";
import { ExtraMachineFeatures } from "@abstractions/machine-specfic";
import { emuMuteSoundAction } from "@state/emulator-panel-reducer";
import {
  spectrumBeamPositionAction,
  spectrumFastLoadAction,
} from "@state/spectrum-specific-reducer";
import { executeKliveCommand } from "@abstractions/common-commands";
import { getVmEngineService } from "@ext-core/vm-engine-service";
import { ZxSpectrumCoreBase } from "@ext/vm-zx-spectrum/ZxSpectrumCoreBase";
import { emuToMainMessenger } from "../common-ui/services/EmuToMainMessenger";

const Root = styles.div`
  display: flex;
  flex-shrink: 0;
  flex-grow: 0;
  height: 40px;
  width: 100%;
  padding: 0px 4px;
  background-color: var(--toolbar-active-background-color);
  box-sizing: border-box;
  align-items: center;
  justify-content: start;
  font-size: 0.9em;
`;

interface Props {
  executionState?: number;
  showKeyboard?: boolean;
  showBeam?: boolean;
  extraFeatures?: ExtraMachineFeatures[];
  muted?: boolean;
  fastLoad?: boolean;
  loadMode?: boolean;
}

interface State {
  hasEngine: boolean;
}

/**
 * Represents the toolbar of the emulator
 */
export class Toolbar extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      hasEngine: getVmEngineService()?.hasEngine,
    };
  }

  componentDidMount(): void {
    getVmEngineService().vmEngineChanged.on(this.vmChange);
  }

  componentWillUnmount(): void {
    getVmEngineService().vmEngineChanged.off(this.vmChange);
  }

  render() {
    const engine = getVmEngineService();
    const executionState = this.props.executionState ?? 0;
    const machineControlButtons = [
      <ToolbarIconButton
        key="play"
        iconName="play"
        fill="lightgreen"
        title="Start"
        enable={
          this.state.hasEngine &&
          (executionState === 0 || executionState === 3 || executionState === 5)
        }
        clicked={async () => {
          await engine.start();
        }}
      />,
      <ToolbarIconButton
        key="pause"
        iconName="pause"
        fill="lightblue"
        title="Pause"
        enable={this.state.hasEngine && executionState === 1}
        clicked={async () => await engine.pause()}
      />,
      <ToolbarIconButton
        key="stop"
        iconName="stop"
        fill="orangered"
        title="Stop"
        enable={
          this.state.hasEngine && (executionState === 1 || executionState === 3)
        }
        clicked={async () => await engine.stop()}
      />,
      <ToolbarIconButton
        key="restart"
        iconName="restart"
        fill="lightgreen"
        title="Restart"
        size={22}
        highlightSize={26}
        enable={
          this.state.hasEngine && (executionState === 1 || executionState === 3)
        }
        clicked={async () => await engine.restart()}
      />,
      <ToolbarSeparator key="sep-0" />,
      <ToolbarIconButton
        key="debug"
        iconName="debug"
        fill="lightgreen"
        title="Debug"
        size={20}
        highlightSize={24}
        enable={
          this.state.hasEngine &&
          (executionState === 0 || executionState === 3 || executionState === 5)
        }
        clicked={async () => await engine.startDebug()}
      />,
      <ToolbarIconButton
        key="step-into"
        iconName="step-into"
        fill="lightblue"
        title="Step into"
        enable={this.state.hasEngine && executionState === 3}
        clicked={async () => await engine.stepInto()}
      />,
      <ToolbarIconButton
        key="step-over"
        iconName="step-over"
        fill="lightblue"
        title="Step over"
        enable={this.state.hasEngine && executionState === 3}
        clicked={async () => await engine.stepOver()}
      />,
      <ToolbarIconButton
        key="step-out"
        iconName="step-out"
        fill="lightblue"
        title="Step out"
        enable={this.state.hasEngine && executionState === 3}
        clicked={async () => await engine.stepOut()}
      />,
      <ToolbarSeparator key="sep-1" />,
      <ToolbarIconButton
        key="keyboard"
        iconName="keyboard"
        title="Toggle keyboard"
        selected={this.props.showKeyboard}
        clicked={() =>
          executeKliveCommand(
            this.props.showKeyboard ? "hideKeyboard" : "showKeyboard"
          )
        }
        highlightSize={32}
      />,
      <ToolbarSeparator key="sep-2" />,
    ];
    const soundButtons = this.props.extraFeatures.includes("Sound")
      ? [
          <ToolbarIconButton
            key="mute"
            iconName={this.props.muted ? "unmute" : "mute"}
            title={this.props.muted ? "Unmute sound" : "Mute sound"}
            clicked={() => dispatch(emuMuteSoundAction(!this.props.muted))}
          />,
          <ToolbarSeparator key="sep3" />,
        ]
      : null;
    const beamButtons = this.props.extraFeatures.includes("UlaDebug")
      ? [
          <ToolbarIconButton
            key="beam-position"
            iconName="beam-position"
            fill="#ff80ff"
            title="Show ULA position"
            selected={this.props.showBeam}
            clicked={() =>
              dispatch(spectrumBeamPositionAction(!this.props.showBeam))
            }
          />,
          <ToolbarSeparator key="sep-4" />,
        ]
      : null;
    const tapeButtons = this.props.extraFeatures.includes("Tape")
      ? [
          <ToolbarIconButton
            key="fastLoad"
            iconName="rocket"
            title="Fast LOAD mode"
            selected={this.props.fastLoad}
            clicked={() =>
              dispatch(spectrumFastLoadAction(!this.props.fastLoad))
            }
          />,
          <ToolbarIconButton
            key="reverse-tape"
            iconName="reverse-tape"
            title="Rewind the tape"
            enable={!this.props.loadMode}
            clicked={async () =>
              await (
                engine.getEngine() as ZxSpectrumCoreBase
              ).initTapeContents()
            }
          />,
          <ToolbarSeparator key="sep-5" />,
        ]
      : null;
    const z88Buttons = this.props.extraFeatures.includes("Z88Cards")
      ? [
          <ToolbarIconButton
            key="z88Card"
            iconName="repo-push"
            title="Manage Z88 cards"
            clicked={async () => {
              await emuToMainMessenger.sendMessage({
                type: "ManageZ88Cards",
              });
            }}
          />,
        ]
      : null;
    return (
      <Root>
        {machineControlButtons}
        {soundButtons}
        {beamButtons}
        {tapeButtons}
        {z88Buttons}
      </Root>
    );
  }

  vmChange = () => {
    this.setState({
      hasEngine: true,
    });
  };
}

export default connect((state: AppState) => {
  return {
    executionState: state.emulatorPanel.executionState,
    showKeyboard: state.emuViewOptions.showKeyboard,
    showBeam: state?.spectrumSpecific?.showBeamPosition,
    extraFeatures: state.emulatorPanel.extraFeatures ?? [],
    muted: state.emulatorPanel.muted,
    fastLoad: state.spectrumSpecific?.fastLoad,
    loadMode: state.spectrumSpecific?.loadMode,
  };
}, null)(Toolbar);
