// packages/klive-emu/src/renderer/emulator/EmulatorPanel.tsx
import * as React from "react";
import { useSelector } from "react-redux";
import ReactResizeDetector from "react-resize-detector";
import { AppState } from "../../shared/state/AppState";
import { VirtualMachineCoreBase } from "../machines/VirtualMachineCoreBase";
import {
  vmEngineService,
  VmStateChangedArgs,
} from "../machines/vm-engine-service";
import BeamOverlay from "./BeamOverlay";
import ExecutionStateOverlay from "./ExecutionStateOverlay";
import styles from "styled-components";
import { useEffect, useRef, useState } from "react";

const TURNED_OFF_MESSAGE =
  "Not yet started. Press F5 to start or Ctrl+F5 to debug machine.";

/**
 * Represents the display panel of the emulator
 */
export default function EmulatorPanel() {
  const hostRectangle = useRef<DOMRect>();
  const screenRectangle = useRef<DOMRect>();

  // --- State variables
  const [windowWidth, setWindowWidth] = useState(0);
  const [windowHeight, setWindowHeight] = useState(0);
  const [canvasWidth, setCanvasWidth] = useState(0);
  const [canvasHeight, setCanvasHeight] = useState(0);
  const [overlay, setOverlay] = useState(TURNED_OFF_MESSAGE);
  const [showOverlay, setShowOverlay] = useState(true);
  const [tactToDisplay, setTactToDisplay] = useState(0);

  // --- App state selectors
  const executionState = useSelector(
    (s: AppState) => s.emulatorPanel.executionState
  );
  const showBeam = useSelector(
    (s: AppState) => s?.spectrumSpecific?.showBeamPosition
  );

  // --- Element dimensions
  let shadowCanvasWidth = 0;
  let shadowCanvasHeight = 0;
  let calcCount = 0;

  // --- Element references
  const hostElement: React.RefObject<HTMLDivElement> = React.createRef();
  const screenElement: React.RefObject<HTMLCanvasElement> = React.createRef();
  const shadowScreenElement: React.RefObject<HTMLCanvasElement> =
    React.createRef();

  let imageBuffer: ArrayBuffer;
  let imageBuffer8: Uint8Array;
  let pixelData: Uint32Array;

  let pressedKeys: Record<string, boolean> = {};

  // --- Prepare the virtual machine engine
  let engine: VirtualMachineCoreBase | null = null;

  useEffect(() => {
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    vmEngineService.vmEngineChanged.on(vmChange);
    vmEngineService.executionStateChanged.on(executionStateChange);
    calculateDimensions();
    if (vmEngineService.hasEngine) {
      engine = vmEngineService.getEngine();
      vmEngineService.screenRefreshed.on(displayScreenData);
      calculateDimensions();
      configureScreen();
    }

    return () => {
      // --- Unmount
      if (engine) {
        vmEngineService.screenRefreshed.off(displayScreenData);
        vmEngineService.vmEngineChanged.off(vmChange);
        vmEngineService.executionStateChanged.on(executionStateChange);
      }
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
    };
  });

  return (
    <Root ref={hostElement} tabIndex={-1}>
      <Screen
        style={{
          width: `${canvasWidth}px`,
          height: `${canvasHeight}px`,
        }}
        onClick={() => setShowOverlay(true)}
      >
        {executionState === 3 && showBeam && (
          <BeamOverlay
            key={calcCount}
            panelRectangle={hostRectangle.current}
            screenRectangle={screenRectangle.current}
            width={windowWidth}
            height={windowHeight}
            tactToDisplay={tactToDisplay}
          />
        )}
        {showOverlay && (
          <ExecutionStateOverlay
            text={overlay}
            clicked={() => {
              setShowOverlay(false);
            }}
          />
        )}
        <canvas ref={screenElement} width={canvasWidth} height={canvasHeight} />
        <canvas
          ref={shadowScreenElement}
          style={{ display: "none" }}
          width={shadowCanvasWidth}
          height={shadowCanvasHeight}
        />
      </Screen>
      <ReactResizeDetector
        handleWidth
        handleHeight
        onResize={calculateDimensions}
      />
    </Root>
  );

  function vmChange(): void {
    if (engine) {
      vmEngineService.screenRefreshed.off(displayScreenData);
    }
    engine = vmEngineService.getEngine();
    if (engine) {
      vmEngineService.screenRefreshed.on(displayScreenData);
    }
    calculateDimensions();
    configureScreen();
    hideDisplayData();
    setOverlay(TURNED_OFF_MESSAGE);
  }

  function executionStateChange(args: VmStateChangedArgs): void {
    calculateDimensions();
    let overlay = "";
    switch (args.newState) {
      case 1:
        overlay = args.isDebug ? "Debug mode" : "";
        break;
      case 3:
        overlay = "Paused";
        const state = engine.getMachineState();
        setTactToDisplay(state.lastRenderedFrameTact % state.tactsInFrame);
        displayScreenData();
        break;
      case 5:
        overlay = "Stopped";
        break;
      default:
        overlay = "";
        break;
    }
    setOverlay(overlay);
  }

  function handleKeyDown(e: KeyboardEvent): void {
    handleKey(e, true);
  }

  function handleKeyUp(e: KeyboardEvent): void {
    handleKey(e, false);
  }

  // --- Calculate the dimensions so that the virtual machine display fits the screen
  function calculateDimensions(): void {
    if (!hostElement?.current || !vmEngineService.hasEngine) {
      return;
    }
    hostRectangle.current = hostElement.current.getBoundingClientRect();
    screenRectangle.current = screenElement.current.getBoundingClientRect();
    const clientWidth = hostElement.current.offsetWidth;
    const clientHeight = hostElement.current.offsetHeight;
    const width = vmEngineService.getEngine().screenWidth;
    const height = vmEngineService.getEngine().screenHeight;
    let widthRatio = Math.floor((clientWidth - 8) / width);
    if (widthRatio < 1) widthRatio = 1;
    let heightRatio = Math.floor((clientHeight - 8) / height);
    if (heightRatio < 1) heightRatio = 1;
    const ratio = Math.min(widthRatio, heightRatio);
    setCanvasWidth(width * ratio);
    setCanvasHeight(height * ratio);
    shadowCanvasWidth = width;
    shadowCanvasHeight = height;
    setWindowWidth(hostRectangle.current.width);
    setWindowHeight(hostRectangle.current.height);
    calcCount = calcCount + 1;
    shadowScreenElement.current.width = width;
    shadowScreenElement.current.height = height;
  }

  // --- Setup the screen buffers
  function configureScreen(): void {
    const dataLen = shadowCanvasWidth * shadowCanvasHeight * 4;
    imageBuffer = new ArrayBuffer(dataLen);
    imageBuffer8 = new Uint8Array(imageBuffer);
    pixelData = new Uint32Array(imageBuffer);
  }

  // --- Displays the screen
  function displayScreenData(): void {
    const screenEl = screenElement.current;
    const shadowScreenEl = shadowScreenElement.current;
    if (!screenEl || !shadowScreenEl) {
      return;
    }

    const shadowCtx = shadowScreenEl.getContext("2d");
    if (!shadowCtx) return;

    shadowCtx.imageSmoothingEnabled = false;
    const shadowImageData = shadowCtx.getImageData(
      0,
      0,
      shadowScreenEl.width,
      shadowScreenEl.height
    );
    const screenCtx = screenEl.getContext("2d");
    let j = 0;

    const screenData = engine.getScreenData();
    for (let i = 0; i < shadowCanvasWidth * shadowCanvasHeight; i++) {
      pixelData[j++] = screenData[i];
    }
    shadowImageData.data.set(imageBuffer8);
    shadowCtx.putImageData(shadowImageData, 0, 0);
    if (screenCtx) {
      screenCtx.imageSmoothingEnabled = false;
      screenCtx.drawImage(shadowScreenEl, 0, 0, canvasWidth, canvasHeight);
    }
  }

  // --- Hide the display
  function hideDisplayData(): void {
    const screenEl = screenElement.current;
    if (!screenEl) return;

    const screenCtx = screenEl.getContext("2d");
    if (screenCtx) {
      screenCtx.clearRect(0, 0, screenEl.width, screenEl.height);
    }
  }

  function handleKey(e: KeyboardEvent, isDown: boolean): void {
    if (!e || executionState !== 1) return;

    // --- Special key: both Shift released
    if (
      (e.code === "ShiftLeft" || e.code === "ShiftRight") &&
      e.shiftKey === false &&
      !isDown
    ) {
      handleMappedKey("ShiftLeft", false);
      handleMappedKey("ShiftRight", false);
    } else {
      handleMappedKey(e.code, isDown);
    }
    if (isDown) {
      pressedKeys[e.code.toString()] = true;
    } else {
      delete pressedKeys[e.code.toString()];
    }
  }

  function handleMappedKey(code: string, isDown: boolean): void {
    if (engine) {
      engine.handlePhysicalKey(code, isDown);
    }
  }
}

// --- Helper component tags
const Root = styles.div`
  display: flex;
  flex-direction: row;
  overflow: hidden;
  flex-shrink: 0;
  flex-grow: 0;
  height: 100%;
  width: 100%;
  background-color: var(--emulator-background-color);
  box-sizing: border-box;
  justify-content: center;
  align-items: center;
  outline: none;
`;

const Screen = styles.div`
  background-color: #404040;
`;

// src/renderer/controls/EmulatorPanel.svelte
<script>
  import { onMount } from "svelte";
  import { createRendererProcessStateAware } from "../rendererProcessStore";
  import { emulatorSetZoomAction } from "../../shared/state/redux-emulator-state";
  import { getSpectrumEngine } from "../spectrum-loader";
  import { pcKeyNames, currentKeyMappings } from "../spectrum/spectrum-keys";

  const stateAware = createRendererProcessStateAware("emulatorPanelState");
  let spectrum;
  let frameCount = 0;

  let width = 0;
  let height = 0;

  let canvasWidth;
  let canvasHeight;

  let screen;
  let shadowScreen;

  let clientWidth;
  let clientHeight;
  let emulatorStyle;

  onMount(async () => {
    spectrum = await getSpectrumEngine();
    spectrum.screenRefreshed.on(onScreenRefreshed);
    width = spectrum.screenWidth;
    height = spectrum.screenHeight;
    calculateDimensions(clientWidth, clientHeight, width, height);
    configureScreen();
    configureSound();
  });

  // --- Respond to panel size changes
  $: {
    calculateDimensions(clientWidth, clientHeight, width, height);
  }

  let imageBuffer;
  let imageBuffer8;
  let pixelData;

  function configureScreen() {
    const dataLen = width * height * 4;
    imageBuffer = new ArrayBuffer(dataLen);
    imageBuffer8 = new Uint8Array(imageBuffer);
    pixelData = new Uint32Array(imageBuffer);
  }

  function configureSound() {
    const audioCtx = new AudioContext();
    const sampleRate = audioCtx.sampleRate;
    audioCtx.close();
    spectrum.setAudioSampleRate(sampleRate);
  }

  function calculateDimensions(clientWidth, clientHeight, width, height) {
    let widthRatio = Math.floor((clientWidth - 8) / width);
    if (widthRatio < 1) widthRatio = 1;
    let heightRatio = Math.floor((clientHeight - 8) / height);
    if (heightRatio < 1) heightRatio = 1;
    const ratio = Math.min(widthRatio, heightRatio);
    stateAware.dispatch(emulatorSetZoomAction(ratio)());
    canvasWidth = width * ratio;
    canvasHeight = height * ratio;
    emulatorStyle = `width:${canvasWidth}px; height:${canvasHeight}px`;

    if (!shadowScreen || !screen) return;
    shadowScreen.width = width;
    shadowScreen.height = height;
    const shadowCtx = shadowScreen.getContext("2d");
    if (shadowCtx) {
      shadowCtx.canvas.width = width;
      shadowCtx.canvas.height = height;
    }
    const screenCtx = screen.getContext("2d");
    if (screenCtx) {
      screenCtx.canvas.width = width * ratio;
      screenCtx.canvas.height = height * ratio;
    }
  }

  function onScreenRefreshed() {
    frameCount++;
    displayScreenData();
  }

  function displayScreenData() {
    const shadowCtx = shadowScreen.getContext("2d");
    if (!shadowCtx) return;
    const shadowImageData = shadowCtx.getImageData(
      0,
      0,
      shadowScreen.width,
      shadowScreen.height
    );
    const screenCtx = screen.getContext("2d");
    let j = 0;

    const screenData = spectrum.getScreenData();
    for (let i = 0; i < width * height; i++) {
      pixelData[j++] = screenData[i];
    }
    shadowImageData.data.set(imageBuffer8);
    shadowCtx.putImageData(shadowImageData, 0, 0);
    if (screenCtx) {
      screenCtx.imageSmoothingEnabled = false;
      screenCtx.drawImage(shadowScreen, 0, 0, screen.width, screen.height);
    }
  }

  function handleKey(e, status) {
    const key = pcKeyNames.get(e.code);
    if (!key) return;
    const mapping = currentKeyMappings.get(key);
    if (mapping) {
      spectrum.setKeyStatus(mapping.zxPrimary, status);
      if (mapping.zxSecondary) {
        spectrum.setKeyStatus(mapping.zxSecondary, status);
      }
    }
  }
</script>

<style>
  .emulator-panel {
    display: flex;
    overflow: hidden;
    flex-shrink: 1;
    flex-grow: 1;
    height: 100%;
    width: 100%;
    /*padding: 8px 12px; */
    background-color: var(--emulator-background-color);
    box-sizing: border-box;
    justify-content: center;
    align-items: center;
    outline: none;
  }

  .emulator-screen {
    background-color: yellow;
  }
</style>

<svelte:window
  on:keydown={e => handleKey(e, true)}
  on:keyup={e => handleKey(e, false)} />
<div tabindex="-1" class="emulator-panel" bind:clientWidth bind:clientHeight>
  <div class="emulator-screen" style={emulatorStyle}>
    <canvas bind:this={screen} />
    <canvas bind:this={shadowScreen} style="display:none" />
  </div>
</div>
